@ECHO OFF

IF DEFINED YAWDS_HOME GOTO END

:: setting specific environment variables
SET YAWDS_HOME=%~dp0..\..
SET YAWDS_STACK_PATH=%~dp0..\

:: binary tools
SET YAWDS_TOOLS_PATH=%~dp0..\tools

:: node
SET NODE_HOME=%YAWDS_STACK_PATH%\node

:: embedded browsers
SET YAWDS_HOME_PHANTOMJS=%YAWDS_STACK_PATH%\phantomjs
SET PHANTOMJS_BIN=%YAWDS_HOME_PHANTOMJS%\phantomjs.exe
SET YAWDS_HOME_SLIMERJS=%YAWDS_STACK_PATH%\slimerjs
SET SLIMERJS_BIN=%YAWDS_STACK_PATH%\slimerjs\slimerjs.bat
SET SLIMERJSLAUNCHER=%YAWDS_STACK_PATH%\slimerjs\xulrunner\xulrunner.exe
SET YAWDS_HOME_CASPERJS=%YAWDS_STACK_PATH%\casperjs\batchbin

:: ruby
SET YAWDS_HOME_RUBY=%YAWDS_STACK_PATH%\ruby\bin

:: update PATH
SET PATH=%NODE_HOME%;%YAWDS_HOME_PHANTOMJS%;%YAWDS_HOME_RUBY%;%YAWDS_HOME_CASPERJS%;%YAWDS_HOME_SLIMERJS%;%YAWDS_TOOLS_PATH%;%YAWDS_TOOLS_PATH%\win-bash;%PATH%

:END
